
on:
  push:
    branches:
      - staging
name: ğŸš€ Deployement (@staging) of Edulen -> Github to Web server
jobs:
  web-deploy:
    name: ğŸ‰ Deploying on staging
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: myedulend.com
          username:  ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}

